### PR TITLE
Import foreign schema

### PR DESCRIPTION
**Pull request by rjuju**
PFA some patches to do minor cleanup, add compatibility until current master and add support for IMPORT FOREIGN SCHEMA.

Feel free to ask me to change anything if you don't agree with this implementation or any other stuff.

### CODE REVIEW

**Comment by cbandy** [comment]
Maybe this also addresses #3?

**Comment by rjuju** [comment]
I didn't see this issue :/ Yes, this PR also fixes it.

**Comment by rjuju** [comment]
Update: After reading the postgres_fdw documentation, I realize that the "import_not_null" and "import_default" options were missing, so I replaced last commit to add support for them (import_collate is not handled, since it doesn't seem supported by sqlite3).  While at it, I also made sure that sqlite objects were not kept open in case of error in the import foreign schema function.

**Comment by gleu** [comment]
Thanks Julien, I merged your code. I added a small fix so that we don't get system tables in Postgres. Other than that, got it all. Thanks again.

**Comment by rjuju** [comment]
Thanks!

Sorry about omitting check for system tables.

**Comment by gleu** [comment]
No problem. Thank you for the patch :)

**Comment by gleu** [comment]
Thanks. This is done with 181ed38.

**Pull request merged**
